sudo: required
language: php
services:
    - docker

php:
    - 5.6
    - 7.0

before_install:
    docker pull phpunit/phpunit
before_script:
    composer install
script: docker run -v $(pwd):/app phpunit/phpunit --bootstrap vendor/autoload.php --coverage-text --configuration phpunit.xml
